name: Deploy Personal Website to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  SITE_TITLE: "Your Name - Personal Website"  # Customize this
  SITE_URL: "https://yourusername.github.io" # Or custom domain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll and plugins
        run: |
          gem install jekyll
          gem install jekyll-seo-tag jekyll-sitemap  # SEO plugins

      - name: Configure personal settings
        run: |
          # Creates config file if doesn't exist
          if [ ! -f _config.yml ]; then
            echo "title: ${{ env.SITE_TITLE }}" > _config.yml
            echo "url: ${{ env.SITE_URL }}" >> _config.yml
            echo "theme: minima" >> _config.yml  # Default theme
            echo "plugins:" >> _config.yml
            echo "  - jekyll-seo-tag" >> _config.yml
            echo "  - jekyll-sitemap" >> _config.yml
          fi

      - name: Build site
        run: jekyll build --trace
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
